# Generated by Django 3.2.13 on 2022-08-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='user_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
