# Generated by Django 3.2.13 on 2022-09-30 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productvariant_product_sku'),
        ('actions', '0002_auto_20220813_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ('-date',)},
        ),
        migrations.RemoveField(
            model_name='like',
            name='vote',
        ),
        migrations.AlterField(
            model_name='like',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_like', to='product.product'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user_id', 'product'), name='Unique user like'),
        ),
    ]
