# Generated by Django 3.2.13 on 2022-09-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0005_alter_channel_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('country', 'currency_code')},
        ),
    ]
