# Generated by Django 3.2.13 on 2022-09-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0007_alter_channel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255),
        ),
    ]
