# Generated by Django 3.2.13 on 2022-05-20 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantChannelListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_in_listings', models.BooleanField(default=True)),
                ('available_to_purchase', models.BooleanField(default=True)),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_listings', to='channel.channel')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_listings', to='product.productvariant')),
            ],
            options={
                'ordering': ('pk',),
                'unique_together': {('product_variant', 'channel')},
            },
        ),
    ]
