# Generated by Django 3.2.13 on 2022-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productvariantchannellisting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariantchannellisting',
            options={'ordering': ('pk',), 'verbose_name': 'ProductVariantChannelListing', 'verbose_name_plural': 'ProductVariantChannelListings'},
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
