# Generated by Django 3.2.13 on 2022-05-20 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20220520_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='type',
            field=models.CharField(choices=[('IMAGE', 'An uploaded image or an URL to an image'), ('VIDEO', 'An uploaded video or an URL to an external video')], default='IMAGE', max_length=32),
        ),
        migrations.AlterField(
            model_name='productvariantchannellisting',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='productvariantchannellisting',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
