# Generated by Django 3.2.13 on 2022-05-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20220520_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantchannellisting',
            name='is_bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
