# Generated by Django 3.2.13 on 2022-05-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_default_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=255, unique=True),
        ),
    ]
