# Generated by Django 3.2.13 on 2022-08-08 08:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20220705_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product_sku',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=255, null=True, unique=True),
        ),
    ]
