# Generated by Django 3.2.13 on 2022-08-10 09:05

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productvariant_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='product_sku',
            field=models.CharField(blank=True, default=product.models.generate_hex, max_length=255, null=True, unique=True),
        ),
    ]
